### ISSUE TITLE
Metropolis–Hastings doesn't iterate correctly

### ISSUE THREAD

**Issue by DianaAvendanoVazquez** [DCIDA2019/dcida2020ii-DianaAvendanoVazquez#1]
@alxogm 
En el código que comenzamos en la clase del [método de metrópolis](https://github.com/DCIDA2019/dcida2020ii-DianaAvendanoVazquez/blob/master/Oct_16/Mtodo_metropolis_lineal.ipynb) tengo el problema que en el **if** sólo itera 4 veces, por lo que en teoría debería en mis 4 puntos encontrar los valores correctos de m y de b para mi ecuación lineal.

Pero cuando meto el plot en el **if** me plotea sólo un punto, y cuando lo saco del if y lo dejo en el **for** me plotea los mil puntitos de colores, pero al final no tengo los valores reales de m y de b (que ya sabemos cuanles son por el ejercicio anterior).

No sé si el problema real es la finición de la función de mi **Likelihood**, prque eso fue lo que entendí de la presentación que nos dió, pero en wikipedia vi que a partir de Bayes sacaban el ratio de las probabilidades, pero tampoco supe bien cómo hacerlo. Me podría indicar qué está mal y ayudar a hacerlo? gracias.

**Comment by DianaAvendanoVazquez** [comment]
Acabo deagregar prints y me di cuenta que adentro del **if** los valores de **m** y **b** no cambian, aún no sé cómo arreglar el problema, pero igual sigo creyendo que mi problema principal es la definición de mi likelihood

**Comment by DianaAvendanoVazquez** [comment]
Agregué más pasos a mi programa y mientras más pasos agregaba en ligar de acercarse más a los valores reales de **m** y de **b** crecen.

**Comment by alxogm** [comment]
Hola Diana, hay varias cosas mal en el programa. Te pongo algunos comentarios que espero te ayuden. 

A.- Respecto a la función Likelihood. El likelihood total es un producto, si, pero lo que tienes escrito no corresponde con la definición de un likelihood Gaussiano, mira la ecuación en la diapositiva 22. Si lo que estás usando es el logaritmo del Likelihood, entonces (1) llamale LnLikelihood a tu función para evitar confusión, y (2) nota que el producto se convierte en sumatoria, mira la diapositiva 23. 
En clase mencione que en general es mejor trabajar con el logaritmo del likelihood, para evitar trabajar con números grandes que pueden resultar de la exponencial...

B.- Respecto al algoritmo de metropolis. Lo que tienes escrito en código no se corresponde con los pasos que se indican en la diapositiva 35. Te los escribiré aquí para intentar ser lo mas explicita posible. 
       1.- Define un punto de inicio  para los parámetros (Esto si lo tienes). Calcula el posterior y resérvalo (Esto no lo tienes)
       2.- Genera un nuevo punto del espacio de parámetros  a partir de una distribución Gausiana  centrada en el punto inicial (el del paso 1) y con  una dispersión $sigma_0$ (Este ultimo parámetros puedes ponerlo de momento como $sigma_0=0.1$ por ejemplo). 
            Lo que tu hiciste fue generar un punto uniforme y le restaste 0.5, y luego lo sumaste al punto que definiste en 1, esto es muy diferente de la instrucción... asegúrate de hacerlo como se indica. Tip utiliza la función https://numpy.org/doc/stable/reference/random/generated/numpy.random.normal.html
      3.- Si el posterior del nuevo punto  (qué debes calcular) es mayor que el del punto inicial, entonces guarda el nuevo punto y reemplaza el viejo por el nuevo. (Esto lo tienes, pero como los puntos 1  y 2 no son correctos, entonces no funciona, corrigiendo 1 y 2, 3 debe funcionar.) 
      4.- Si el posterior del punto nuevo es menor que el del punto inicial, entonces genera un numero uniforme entre 0 y 1, si P(nuevo)/P(viejo) (Donde P es el posterior, esto es lo mismo que el ratio al que te refieres que viste en wikipedia), es mayor que el numero que generaste entonces guarda el nuevo punto y reemplaza el viejo por el nuevo. En el caso contrario, descartas el punto nuevo y dejas el punto original sin alterarlo. 

**Para los puntos 3 y 4 toma en cuenta que hablé del Posterior, pero si en el punto A usaste el logaritmo del posterior, entonces las comparaciones se hacen entre logaritmos, es decir que el ratio se convierte en una resta y debes sacar el logaritmo del punto aleatorio, para compararlos. 

    5.- En este paso tienes que o bien reemplazaste el punto original por el nuevo, o te quedaste con el original, y este se utiliza para volver al punto 2, y repetir el procedimiento. Esto en efecto es lo que se traduce en el ciclo FOR. 

Mi recomendación es que antes de hacer mil pasos, empieces con un ciclo de pocos pasos,  2 o 3 son suficientes para verificar que el algoritmo está funcionando y haciendo cada paso correctamente. Puedes imprimir los valores de los parámetros generados, y de los posteriores (o logaritmo del posterior) y verificar que la decisión en los puntos 3 y 4 se están haciendo adecuadamente.  

**Nota que en A, hable del likelihood, y en B hablé del posterior, esto porque asumo que tendrás otra función que multiplique el Likelihood por el Prior para construir el Posterior (O bien sume los logaritmos del prior y del likelihood para obtener el logaritmo del posterior).

**Comment by DianaAvendanoVazquez** [comment]
No me entendió mi duda.

Creo que nuestra confusión (de ambas) viene a partir del cambio constante de notación e intrucciones en la diapositiva 28 de la última presentación.
Y además no me queda claro cuáles son prior y el posterior, me podría decir con otras palabras qué funciones son o cuáles representan? el posterior el el número random con el que voy a comparar mi punto i?
